// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOA_CA2_Cian_Nojus.Data;

#nullable disable

namespace SOA_CA2_Cian_Nojus.Migrations
{
    [DbContext(typeof(SOA_CA2_Cian_NojusContext))]
    partial class SOA_CA2_Cian_NojusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SOA_CA2_Cian_Nojus.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            country = "USA",
                            name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            country = "Japan",
                            name = "Nintendo"
                        });
                });

            modelBuilder.Entity("SOA_CA2_Cian_Nojus.Models.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("developer_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("release_year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            developer_id = 1,
                            genre = "Shooter",
                            release_year = 2001,
                            title = "Halo"
                        },
                        new
                        {
                            Id = 2,
                            developer_id = 1,
                            genre = "Shooter",
                            release_year = 2006,
                            title = "Gears of War"
                        },
                        new
                        {
                            Id = 3,
                            developer_id = 1,
                            genre = "Racing",
                            release_year = 2023,
                            title = "Forza Horizon"
                        },
                        new
                        {
                            Id = 4,
                            developer_id = 2,
                            genre = "Action-Adventure",
                            release_year = 2024,
                            title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 5,
                            developer_id = 2,
                            genre = "Platformer",
                            release_year = 2008,
                            title = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 6,
                            developer_id = 2,
                            genre = "Racing",
                            release_year = 2020,
                            title = "Mario Kart 8 Deluxe"
                        });
                });

            modelBuilder.Entity("SOA_CA2_Cian_Nojus.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            manufacturer = "Microsoft",
                            name = "Xbox"
                        },
                        new
                        {
                            Id = 2,
                            manufacturer = "Nintendo",
                            name = "Nintendo Switch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
